package com.synaway.oneplaces.repository;

/**
 * Repository methods that need custom implementation - cannot be generated by
 * Spring Data.
 * 
 */
public interface SpotRepositoryCustom {
    Long count(Double latitude, Double longitude, Integer radius, int secondsFrom, int secondsTo);
}
